README.md
bootstrap-gruntwork-installer.sh
gruntwork-install

This PR makes our infrastructure installers, which were original in the packer-modules repo, and makes them open source. 
`install-packer-module` is now called `gruntwork-install`. The goal of this script is to make it as easy to install modules from our script-modules repo as it is to use apt-get or yum. Note that this script now uses a generic name (not packer specific) and points at script-modules (not packer-modules). Obviously, we need to configure all of the scripts in script-modules to work with it.
`install-gruntwork-packer-bootstrap-tools.sh` is now called `bootstrap-gruntwork-installer.sh`. You can use this script in a one-liner to install `gruntwork-install` as follows: 
```bash
curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwor …
```

Make our installer scripts open source

---

README.md
_ci/run-tests.sh
bootstrap-gruntwork-installer.sh
circle.yml
gruntwork-install
test/Dockerfile
test/docker-compose.yml
test/integration-test.sh

This PR adds a very basic level of automated tests to the Gruntwork installer. It runs a bare-minimum-end-to-end integration test: run the bootstrap script to install `gruntwork-install` and then run `gruntwork-install` to install a module from script-modules. 
The tests run in a Docker container to keep your local environment clean.

Add basic automated tests

---

README.md
gruntwork-install
test/integration-test.sh

This PR allows us to install modules from repos other than script-modules. Since the plan is to break up terraform-modules and script-modules into many separate repos, this becomes important.

Allow specifying a custom repo for gruntwork-install

---

README.md
gruntwork-install
test/integration-test.sh

This PR allows `gruntwork-install` to install not only source folders under a `modules` directory in GitHub, but also binaries assets uploaded to a GitHub release.
This also removes the script-modules repo as the default, since we are actively moving everything out of it and actually prefer that it's not used anymore. Since `gruntwork-install` is versioned, this shouldn't affect any existing users.

Add support for installing binaries

---

README.md
examples/packer-file-copy/files/foo/bar/test.txt
examples/packer-file-copy/packer-example.json
gruntwork-install
modules/README.md
modules/packer-file-copy/README.md
modules/packer-file-copy/install-scripts/copy-packer-files.sh
modules/packer-file-copy/install.sh

This PR:
1. Adds the `packer-file-copy` Script Module to this repo.
2. Rewrites the top-level README to reflect our now more clear understanding of the role of Gruntwork Script Modules.
I'd also like to propose using the term "Gruntwork Script Module" as a first-class term. At some point, we may further clarify that in addition to "Script Modules" we have other types of modules. For example, the module used to generate a TLS cert for Vault isn't a Script Module, but maybe an "Execution Module".
@brikis98 For now, let me know your thoughts on what's updated in this PR.

Add packer-file-copy script module and rewrite main README.

---

gruntwork-install
modules/dummy-module/README.md
modules/dummy-module/install.sh
test/integration-test.sh

This PR fixes a bug with the `--module-param` args of `gruntwork-install`. We wrap those args in single quotes to handle possible spaces, but in order for that to work correctly, we need to `eval` the args. 
Along the way, I had to do a bit of yak shaving to fix other issues in the tests. Not sure how these passed before?

Fix how module-param args are handled

---

gruntwork-install

Previously, a param was rendering as the literal " 'literal-val' " with single quotes, which was causing the script that was receiving this value to fail. Using double quotes removes the issue.

Fix issue with quotes around module params.

---

bootstrap-gruntwork-installer.sh

One of our customers is on a 32-bit system that identifies its architecture as 686. This should work with 386 binaries, so update the bootstrap script to support that.

Add support for 686

---

bootstrap-gruntwork-installer.sh
gruntwork-install

- Update gruntwork-install to use fetch v0.2.0
- Update gruntwork-install to accept params `--binary-sha256-checksum` and  `--binary-sha512-checksum` which can be used to validate a binary release.

Update fetch to support checksum validation on binary assets.

---

gruntwork-install
test/integration-test.sh

Right now `gruntwork-install` enforces the condition that `GITHUB_OAUTH_TOKEN` is set, but this does not need to be set for public repos (e.g `terragrunt`, `terratest`, and soon `kubergrunt`). This PR adds a simple check to see if the repo can be accessed anonymously (does not 404), and if so, ignore the check.

Allow public repo access

---

gruntwork-install
test/integration-test.sh

The installer supports passing parameters to the module installers. However, in several places it's munging the whitespace and splitting the arguments into multiple args.
This change seeks to maintain args as single, whole args and not split on whitespace.

Preserve whitespace in parameter values and treat as whole args

---

bootstrap-gruntwork-installer.sh
gruntwork-install

This addresses all shellcheck warnings for both the bootstrap script and `gruntwork-install` script.

Address all shellcheck warnings

---

_ci/run-tests.sh
bootstrap-gruntwork-installer.sh
gruntwork-install
test/integration-test.sh
test/no-sudo-test.sh
test/no_sudo/Dockerfile
test/no_sudo/docker-compose.yml

This PR addresses https://github.com/gruntwork-io/gruntwork-installer/issues/48
Specifically, both the bootstrap script and `gruntwork-install` now support an argument `--no-sudo` to allow installing binaries without the use of `sudo`.

Support a no-sudo install (limited to binaries)

---

README.md
gruntwork-install

(NOTE: This is related to [this discussion](https://github.com/gruntwork-io/aws-service-catalog/pull/165#discussion_r481421956).)
In some cases, such as the situation linked above, we may wish to use the value of the `--tag` as a reference within an install script. This PR sets an env var to the tag so that the install script can use to avoid these chicken & egg scenarios.

Expose tag value as env var for module install scripts

---

bootstrap-gruntwork-installer.sh

The latest version of fetch fixes a number of important bugs, including:
- Add support for working with GitHub Enterprise.
- Skip Git tags that don't follow SemVer.
- Add support for pagination on Git tags so that you can fetch older tags in repos with many tags.
The last item is especially important, as we now have more repos with many tags.

Update default fetch version

---

bootstrap-gruntwork-installer.sh

This PR updates `fetch` to use the proper logger that was added in https://github.com/gruntwork-io/fetch/pull/90 and released in https://github.com/gruntwork-io/fetch/releases/tag/v0.4.0. I've also bumped the version v0.4.1 to include a minor fix for the usage help text.

Update fetch to version with a proper logger

---

gruntwork-install
test/integration-test.sh

`fetch` now supports a `--ref` parameter that can accept any git ref (branch, tag, or sha), but `gruntwork-install` does not expose it. This PR updates `gruntwork-install` to expose the `ref` parameter.

Expose ref parameter in fetch

---

README.md
test/integration-test.sh

_**This PR was created by git-xargs. See https://github.com/gruntwork-io/prototypes/pull/152 for context.**_ We recently renamed all of our repos to follow the Terraform registry format of  (e.g., ). This PR does a search & replace to update all references to these repos to the new names. GitHub can handle redirects, so in theory, everything should work fine with the old names, but there were so many renames, that to reduce confusion, this will update most of our references to the proper values.

Update all repo names

---

bootstrap-gruntwork-installer.sh
gruntwork-install

Previously we were assuming `amd64` if the arch string contained `64`, but this ignores `arm64` machines like M1 macbook. This fixes that.

Use arm64 if arm64

---

bootstrap-gruntwork-installer.sh
gruntwork-install

* `uname -m` returns `aarch64` on EKS ARM AMIs which causes `get_os_arch_gox_format` to return `amd64` rather than `arm64`
* fetch `0.4.1` has no ARM build
* add case for `aarch64` returning `arm64`
* bump fetch version
Tested on x86 + ARM builds

fix aarch64 fetch install

---

README.md
bootstrap-gruntwork-installer.sh
examples/packer-file-copy/packer-example.json

Addresses part of https://github.com/gruntwork-io/cloud-chasers/issues/32
We've updated the default branch to `main`. This PR updates all the references in this repo to the new correct ones.
Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).
Updated old default branch references as we've switched to `main`.

Update old default branch references.

---

README.md
bootstrap-gruntwork-installer.sh
examples/packer-file-copy/packer-example.json

Addresses part of https://github.com/gruntwork-io/cloud-chasers/issues/32
We've updated the default branch of this repo to `main`. However we still have a copy of the old default branch that we are allowing to get stale. No updates after this PR should be merged into it. We will delete that branch on February 1, 2023.
Note: This PR will be merged onto the old default branch, not `main`.
When someone uses the old default branch, they'll see this notice:
Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).
Added a deprecation notice warning users to specify a tagged release. We've updated the default branch to `main`. **NOTE**: We will delete the old default branch, `master`, on February 1, 2023, to allow …

Output a Deprecation Notice on old branch

---

bootstrap-gruntwork-installer.sh

Fixes [CORE-797] #85 
Fixes [vulnerability](https://github.com/advisories/GHSA-69cg-p879-7622) in a dependency of the fetch package.
Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).
Added / Removed / Updated [X].
[CORE-797]: https://gruntwork.atlassian.net/browse/CORE-797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CORE-797] Fix fetch package vulnerability

---

gruntwork-install
modules/mixed-args-module/README.md
modules/mixed-args-module/install.sh
test/integration-test.sh

Fixes #91 
Properly handle flags when processing `--module-param`. Previously a flag that was passed like this: `--module-param flag` ended up like this: `--flag flag`. With this change it is properly passed as just `--flag`. 
Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).
Added / Removed / Updated [X].

Support flags
